# Generated by Django 3.2.3 on 2021-11-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.Genre'),
        ),
    ]
